#!/usr/bin/env python3
"""GeocodeBR + City2Graph + NexusDB urban-service demo.

Default mode is fully deterministic and uses synthetic coordinates.

Input modes:
- --geocode-csv: geocode demand/facility CEPs through geocodebr;
- --poi-csv: load real POIs (for example niteroi_pois.csv generated by
  download_niteroi_pois.py) and build a POI proximity graph.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import re
import unicodedata
import time
import urllib.error
import urllib.request
import uuid
from pathlib import Path

import geopandas as gpd
import pandas as pd
from shapely.geometry import Point

import city2graph as c2g


DEFAULT_URL = os.getenv("NEXUSDB_URL", "http://127.0.0.1:7474")
DEFAULT_USER = os.getenv("NEXUSDB_USER", "admin")
DEFAULT_PASSWORD = os.getenv("NEXUSDB_PASSWORD", "")
METRIC_CRS = "EPSG:31983"  # SIRGAS 2000 / UTM 23S — Rio de Janeiro region.


class NexusClient:
    def __init__(self, url: str, user: str, password: str, database: str):
        self.url = url.rstrip("/")
        self.user = user
        self.password = password
        self.database = database

    def post(self, route: str, payload: dict, timeout: int = 180) -> dict:
        req = urllib.request.Request(
            self.url + route,
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Content-Type": "application/json",
                "X-User": self.user,
                "X-Pass": self.password,
                "X-Database": self.database,
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=timeout) as response:
                result = json.load(response)
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"HTTP {exc.code}: {body}") from None
        except urllib.error.URLError as exc:
            raise RuntimeError(f"NexusDB connection failed: {exc}") from None

        if result.get("errors"):
            raise RuntimeError(json.dumps(result, ensure_ascii=False))
        return result

    def cypher(self, query: str) -> dict:
        return self.post(
            "/db/data/cypher",
            {"statements": [{"query": query}]},
        )

    def bulk_nodes(self, rows: list[dict]) -> dict:
        return self.post("/db/data/node/bulk", {"rows": rows})

    def bulk_relationships(self, rows: list[dict]) -> dict:
        return self.post("/db/data/relationship/bulk", {"rows": rows})


def fixture_layers() -> tuple[gpd.GeoDataFrame, gpd.GeoDataFrame]:
    """Small synthetic metric fixture.

    Coordinates are deliberately synthetic. They only create a reproducible
    urban accessibility topology and must not be interpreted as real services.
    """
    demand = pd.DataFrame(
        [
            ("D001", "Demand A", 680000.0, 7463000.0),
            ("D002", "Demand B", 680450.0, 7463250.0),
            ("D003", "Demand C", 680900.0, 7462900.0),
            ("D004", "Demand D", 681350.0, 7463400.0),
            ("D005", "Demand E", 681850.0, 7463000.0),
            ("D006", "Demand F", 682250.0, 7463600.0),
            ("D007", "Demand G", 682900.0, 7462950.0),
            ("D008", "Demand H", 683350.0, 7463500.0),
            ("D009", "Demand I", 684100.0, 7463000.0),
            ("D010", "Demand J", 684700.0, 7463650.0),
        ],
        columns=["external_id", "name", "x", "y"],
    )
    facilities = pd.DataFrame(
        [
            ("F001", "Health Hub", "health", 680700.0, 7463200.0),
            ("F002", "Education Hub", "education", 682000.0, 7463150.0),
            ("F003", "Emergency Hub", "emergency", 683000.0, 7463350.0),
            ("F004", "Food Hub", "food", 684350.0, 7463200.0),
        ],
        columns=["external_id", "name", "category", "x", "y"],
    )

    demand_gdf = gpd.GeoDataFrame(
        demand,
        geometry=[Point(x, y) for x, y in zip(demand.x, demand.y)],
        crs=METRIC_CRS,
    ).set_index("external_id", drop=False)

    facility_gdf = gpd.GeoDataFrame(
        facilities,
        geometry=[Point(x, y) for x, y in zip(facilities.x, facilities.y)],
        crs=METRIC_CRS,
    ).set_index("external_id", drop=False)

    return demand_gdf, facility_gdf


def geocode_layers(csv_path: Path) -> tuple[gpd.GeoDataFrame, gpd.GeoDataFrame]:
    """Resolve CEPs with geocodebr and return metric demand/facility layers."""
    from geocodebr import busca_por_cep

    source = pd.read_csv(csv_path, dtype={"cep": str})
    required = {"external_id", "kind", "cep", "name"}
    missing = required.difference(source.columns)
    if missing:
        raise ValueError(f"CSV missing columns: {sorted(missing)}")

    if not source["kind"].isin(["demand", "facility"]).all():
        raise ValueError("kind must contain only 'demand' or 'facility'")

    ceps = source["cep"].dropna().astype(str).drop_duplicates().tolist()
    result = busca_por_cep(
        cep=ceps,
        h3_res=9,
        resultado_gpd=False,
        verboso=False,
    )
    table = result.to_pandas() if hasattr(result, "to_pandas") else pd.DataFrame(result)
    table = table.dropna(subset=["lat", "lon"])

    if table.empty:
        raise RuntimeError("geocodebr did not return coordinates for the supplied CEPs")

    # A CEP may have multiple CNEFE rows. A representative centroid is enough
    # for this demo; production applications should implement domain-specific
    # disambiguation instead.
    centroid = (
        table.groupby("cep", as_index=False)
        .agg(
            lat=("lat", "mean"),
            lon=("lon", "mean"),
            h3_09=("h3_09", "first"),
            municipio=("municipio", "first"),
            localidade=("localidade", "first"),
        )
    )

    source["cep_norm"] = source["cep"].str.replace("-", "", regex=False)
    centroid["cep_norm"] = centroid["cep"].astype(str).str.replace("-", "", regex=False)
    merged = source.merge(centroid.drop(columns=["cep"]), on="cep_norm", how="left")
    merged = merged.dropna(subset=["lat", "lon"]).copy()

    if len(merged) < 2:
        raise RuntimeError("Too few geocoded points to construct a graph")

    gdf = gpd.GeoDataFrame(
        merged,
        geometry=gpd.points_from_xy(merged["lon"], merged["lat"]),
        crs="EPSG:4674",
    ).to_crs(METRIC_CRS)

    gdf["x"] = gdf.geometry.x
    gdf["y"] = gdf.geometry.y

    demand = gdf[gdf["kind"] == "demand"].copy().set_index("external_id", drop=False)
    facility = gdf[gdf["kind"] == "facility"].copy().set_index("external_id", drop=False)

    if demand.empty or facility.empty:
        raise RuntimeError("Need at least one demand point and one facility")

    return demand, facility


def poi_layer(csv_path: Path) -> gpd.GeoDataFrame:
    """Load a real POI CSV with latitude/longitude and reproject to metric CRS.

    Expected columns are those produced by download_niteroi_pois.py:
    external_id, kind, category, name, address, bairro, cep,
    latitude, longitude, source, source_layer.
    """
    source = pd.read_csv(csv_path, dtype={"external_id": str, "cep": str})
    required = {"external_id", "category", "name", "latitude", "longitude"}
    missing = required.difference(source.columns)
    if missing:
        raise ValueError(f"POI CSV missing columns: {sorted(missing)}")

    source["latitude"] = pd.to_numeric(source["latitude"], errors="coerce")
    source["longitude"] = pd.to_numeric(source["longitude"], errors="coerce")
    source = source.dropna(subset=["latitude", "longitude"]).copy()

    # Basic geographic sanity check for WGS84/SIRGAS-like lon/lat coordinates.
    source = source[
        source["latitude"].between(-90.0, 90.0)
        & source["longitude"].between(-180.0, 180.0)
    ].copy()

    if len(source) < 2:
        raise RuntimeError("POI CSV needs at least two valid coordinate rows")

    # Ensure unique external identifiers. The official downloader generates
    # stable layer/object identifiers, so duplicates indicate malformed input.
    if source["external_id"].duplicated().any():
        dupes = source.loc[source["external_id"].duplicated(), "external_id"].tolist()
        raise ValueError(f"Duplicate external_id values in POI CSV: {dupes[:10]}")

    gdf = gpd.GeoDataFrame(
        source,
        geometry=gpd.points_from_xy(source["longitude"], source["latitude"]),
        crs="EPSG:4326",
    ).to_crs(METRIC_CRS)

    gdf["x"] = gdf.geometry.x
    gdf["y"] = gdf.geometry.y
    return gdf.set_index("external_id", drop=False)


def build_poi_edges(
    pois: gpd.GeoDataFrame,
    radius_m: float,
) -> gpd.GeoDataFrame:
    """Create a POI-to-POI proximity graph with City2Graph."""
    _, edges = c2g.fixed_radius_graph(
        pois,
        radius=radius_m,
        distance_metric="euclidean",
    )
    return edges


def normalize_bairro_name(value) -> str | None:
    """Normalize a bairro label without inventing a geographic assignment."""
    if value is None or pd.isna(value):
        return None
    text = unicodedata.normalize("NFKC", str(value))
    text = re.sub(r"\\s+", " ", text).strip()
    if not text or text.lower() in {"nan", "none", "null", "n/a", "na", "-"}:
        return None
    return text


def bairro_key(name: str) -> str:
    """Stable NexusDB key for a bairro name."""
    canonical = unicodedata.normalize("NFKD", name)
    canonical = "".join(ch for ch in canonical if not unicodedata.combining(ch))
    canonical = re.sub(r"[^a-z0-9]+", "-", canonical.casefold()).strip("-")
    digest = hashlib.sha1(name.casefold().encode("utf-8")).hexdigest()[:8]
    return f"BAIRRO-{canonical[:40]}-{digest}"


def bairro_rows(pois: gpd.GeoDataFrame) -> tuple[list[dict], dict[str, str]]:
    """Build one Bairro node per distinct bairro label present in the POI source."""
    by_folded: dict[str, str] = {}
    for value in pois.get("bairro", pd.Series(dtype=object)):
        name = normalize_bairro_name(value)
        if name:
            by_folded.setdefault(name.casefold(), name)

    rows: list[dict] = []
    lookup: dict[str, str] = {}
    for folded, display_name in sorted(by_folded.items(), key=lambda x: x[1].casefold()):
        key = bairro_key(display_name)
        lookup[folded] = key
        rows.append(
            {
                "key": key,
                "label": "Bairro",
                "properties": {
                    "external_id": key,
                    "name": display_name,
                    "municipality": "Niterói",
                    "state": "RJ",
                    "country": "Brasil",
                    "source": "Prefeitura Municipal de Niterói / SIGeo (bairro attribute)",
                },
            }
        )
    return rows, lookup


def bairro_summary(pois: gpd.GeoDataFrame) -> dict:
    """Summarize POI coverage and service diversity by bairro."""
    if "bairro" not in pois.columns:
        return {}

    frame = pois.copy()
    frame["_bairro_norm"] = frame["bairro"].map(normalize_bairro_name)
    frame = frame.dropna(subset=["_bairro_norm"])
    if frame.empty:
        return {}

    summary = {}
    for bairro, group in frame.groupby("_bairro_norm"):
        categories = sorted(set(group["category"].astype(str)))
        summary[str(bairro)] = {
            "poi_count": int(len(group)),
            "category_count": int(len(categories)),
            "categories": categories,
        }
    return dict(sorted(summary.items(), key=lambda x: x[0].casefold()))


def poi_node_rows(pois: gpd.GeoDataFrame) -> list[dict]:
    """Convert real POIs to NexusDB node-bulk rows."""
    rows: list[dict] = []
    optional = (
        "address",
        "bairro",
        "cep",
        "source",
        "source_layer",
        "latitude",
        "longitude",
    )

    for _, row in pois.iterrows():
        props = {
            "external_id": str(row["external_id"]),
            "name": str(row["name"]),
            "kind": str(row.get("kind", "facility")),
            "category": str(row.get("category", "poi")),
            "x_m": float(row.geometry.x),
            "y_m": float(row.geometry.y),
            "crs": METRIC_CRS,
        }

        for key in optional:
            if key in row and json_value(row[key]) is not None:
                value = json_value(row[key])
                if key in ("latitude", "longitude"):
                    props[key] = float(value)
                else:
                    props[key] = str(value)

        rows.append(
            {
                "key": str(row["external_id"]),
                "label": "POI",
                "properties": props,
            }
        )

    return rows


def import_poi_graph(
    client: NexusClient,
    pois: gpd.GeoDataFrame,
    edges: gpd.GeoDataFrame,
    radius_m: float,
) -> tuple[dict[str, int], dict]:
    """Bulk-load POIs, Bairro nodes, NEAR and LOCATED_IN relationships."""
    poi_payload = poi_node_rows(pois)
    bairros_payload, bairro_lookup = bairro_rows(pois)
    nodes_payload = poi_payload + bairros_payload

    response = client.bulk_nodes(nodes_payload)

    id_map: dict[str, int] = {}
    for item in response.get("resultados", []):
        key = str(item.get("key"))
        node_id = item.get("id")
        if node_id is not None:
            id_map[key] = int(node_id)

    if len(id_map) != len(nodes_payload):
        raise RuntimeError(
            f"NexusDB returned IDs for {len(id_map)}/{len(nodes_payload)} POI+Bairro nodes"
        )

    near_rels = []
    seen_pairs: set[tuple[str, str]] = set()
    for i, (src, dst, distance_m) in enumerate(edge_endpoints(edges)):
        if src == dst:
            continue

        # fixed_radius_graph may expose homogeneous links in either one or both
        # directions. Persist one deterministic semantic NEAR edge per pair.
        pair = tuple(sorted((src, dst)))
        if pair in seen_pairs:
            continue
        seen_pairs.add(pair)

        near_rels.append(
            {
                "key": f"NEAR-{i:06d}",
                "from": id_map[pair[0]],
                "to": id_map[pair[1]],
                "type": "NEAR",
                "properties": {
                    "distance_m": distance_m,
                    "radius_m": float(radius_m),
                    "method": "city2graph.fixed_radius_graph",
                    "semantics": "undirected_proximity",
                },
            }
        )

    located_rels = []
    if "bairro" in pois.columns:
        for i, (_, row) in enumerate(pois.iterrows()):
            bairro = normalize_bairro_name(row.get("bairro"))
            if not bairro:
                continue
            bairro_id_key = bairro_lookup.get(bairro.casefold())
            poi_key = str(row["external_id"])
            if not bairro_id_key or poi_key not in id_map or bairro_id_key not in id_map:
                continue
            located_rels.append(
                {
                    "key": f"LOCATED-IN-{i:06d}",
                    "from": id_map[poi_key],
                    "to": id_map[bairro_id_key],
                    "type": "LOCATED_IN",
                    "properties": {
                        "source": "SIGeo bairro attribute",
                        "assignment": "source_attribute",
                    },
                }
            )

    # Bounded batches avoid oversized HTTP payloads.
    batch_size = 500
    all_rels = near_rels + located_rels
    for offset in range(0, len(all_rels), batch_size):
        client.bulk_relationships(all_rels[offset : offset + batch_size])

    stats = {
        "poi_nodes": len(poi_payload),
        "bairro_nodes": len(bairros_payload),
        "near_relationships": len(near_rels),
        "located_in_relationships": len(located_rels),
        "pois_without_bairro": len(poi_payload) - len(located_rels),
    }
    return id_map, stats


def build_access_edges(
    demand: gpd.GeoDataFrame,
    facility: gpd.GeoDataFrame,
    radius_m: float,
) -> gpd.GeoDataFrame:
    """Create directed demand -> facility accessibility edges."""
    _, edges = c2g.fixed_radius_graph(
        demand,
        radius=radius_m,
        distance_metric="euclidean",
        target_gdf=facility,
    )
    return edges


def json_value(value):
    if pd.isna(value):
        return None
    if hasattr(value, "item"):
        return value.item()
    return value


def node_rows(demand: gpd.GeoDataFrame, facility: gpd.GeoDataFrame) -> list[dict]:
    rows: list[dict] = []

    for _, row in demand.iterrows():
        props = {
            "external_id": str(row["external_id"]),
            "name": str(row["name"]),
            "kind": "demand",
            "x_m": float(row.geometry.x),
            "y_m": float(row.geometry.y),
            "crs": METRIC_CRS,
        }
        for key in ("cep", "h3_09", "municipio", "localidade"):
            if key in row and json_value(row[key]) is not None:
                props[key] = str(json_value(row[key]))
        rows.append(
            {
                "key": str(row["external_id"]),
                "label": "DemandPoint",
                "properties": props,
            }
        )

    for _, row in facility.iterrows():
        props = {
            "external_id": str(row["external_id"]),
            "name": str(row["name"]),
            "kind": "facility",
            "category": str(row.get("category", "service")),
            "x_m": float(row.geometry.x),
            "y_m": float(row.geometry.y),
            "crs": METRIC_CRS,
        }
        for key in ("cep", "h3_09", "municipio", "localidade"):
            if key in row and json_value(row[key]) is not None:
                props[key] = str(json_value(row[key]))
        rows.append(
            {
                "key": str(row["external_id"]),
                "label": "Facility",
                "properties": props,
            }
        )

    return rows


def edge_endpoints(edges: gpd.GeoDataFrame) -> list[tuple[str, str, float]]:
    """Extract City2Graph edge endpoints without assuming only one index layout."""
    out: list[tuple[str, str, float]] = []
    for idx, row in edges.iterrows():
        if isinstance(idx, tuple) and len(idx) >= 2:
            src, dst = str(idx[0]), str(idx[1])
        elif "source" in row and "target" in row:
            src, dst = str(row["source"]), str(row["target"])
        elif "u" in row and "v" in row:
            src, dst = str(row["u"]), str(row["v"])
        else:
            raise RuntimeError(
                "Unsupported City2Graph edge layout. "
                "Expected MultiIndex (source,target) or source/target columns."
            )

        weight = row.get("weight")
        if weight is None or (isinstance(weight, float) and math.isnan(weight)):
            weight = row.geometry.length if row.geometry is not None else 0.0
        out.append((src, dst, float(weight)))
    return out


def import_graph(
    client: NexusClient,
    demand: gpd.GeoDataFrame,
    facility: gpd.GeoDataFrame,
    edges: gpd.GeoDataFrame,
) -> dict[str, int]:
    nodes_payload = node_rows(demand, facility)
    response = client.bulk_nodes(nodes_payload)

    id_map: dict[str, int] = {}
    for item in response.get("resultados", []):
        key = str(item.get("key"))
        node_id = item.get("id")
        if node_id is not None:
            id_map[key] = int(node_id)

    if len(id_map) != len(nodes_payload):
        raise RuntimeError(
            f"NexusDB returned IDs for {len(id_map)}/{len(nodes_payload)} nodes"
        )

    rels = []
    for i, (src, dst, distance_m) in enumerate(edge_endpoints(edges)):
        rels.append(
            {
                "key": f"ACCESS-{i:05d}",
                "from": id_map[src],
                "to": id_map[dst],
                "type": "CAN_REACH",
                "properties": {
                    "distance_m": distance_m,
                    "method": "city2graph.fixed_radius_graph",
                },
            }
        )

    if rels:
        client.bulk_relationships(rels)

    return id_map


def extract_rows(result: dict) -> list:
    return result.get("resultados", [])


def run_algorithms(client: NexusClient) -> dict:
    queries = {
        "degree": "CALL algo.degree();",
        "pagerank": "CALL algo.pageRank(20);",
        "connected_components": "CALL algo.connectedComponents();",
    }
    out = {}
    for name, query in queries.items():
        start = time.perf_counter()
        result = client.cypher(query)
        out[name] = {
            "elapsed_ms": round((time.perf_counter() - start) * 1000.0, 3),
            "rows": extract_rows(result),
        }
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--geocode-csv", type=Path)
    parser.add_argument(
        "--poi-csv",
        type=Path,
        help="POI CSV generated by download_niteroi_pois.py",
    )
    parser.add_argument("--radius-m", type=float, default=1200.0)
    parser.add_argument("--url", default=DEFAULT_URL)
    parser.add_argument("--user", default=DEFAULT_USER)
    parser.add_argument("--password", default=DEFAULT_PASSWORD)
    parser.add_argument("--database")
    parser.add_argument("--output", type=Path, default=Path("output"))
    args = parser.parse_args()

    if args.radius_m <= 0:
        raise SystemExit("--radius-m must be positive")
    if not args.password:
        raise SystemExit("Set NEXUSDB_PASSWORD or pass --password")

    if args.geocode_csv and args.poi_csv:
        raise SystemExit("Use only one of --geocode-csv or --poi-csv")

    database = args.database or (
        "URBAN_GRAPH_" + uuid.uuid4().hex[:8].upper()
    )
    client = NexusClient(args.url, args.user, args.password, database)

    if args.poi_csv:
        mode = "poi_csv"
        pois = poi_layer(args.poi_csv)
        edges = build_poi_edges(pois, args.radius_m)

        print(f"Mode       : {mode}")
        print(f"POIs       : {len(pois)}")
        print(f"Categories : {pois['category'].nunique()}")
        print(f"Edges raw  : {len(edges)}")
        print(f"Radius     : {args.radius_m:.1f} m")
        print(f"Database   : {database}")

        client.cypher(f"CREATE DATABASE {database}")
        ids, import_stats = import_poi_graph(client, pois, edges, args.radius_m)
        algorithms = run_algorithms(client)

        category_counts = (
            pois["category"]
            .astype(str)
            .value_counts()
            .sort_index()
            .to_dict()
        )

        bairros = bairro_summary(pois)

        print(f"Bairros    : {import_stats['bairro_nodes']}")
        print(f"NEAR       : {import_stats['near_relationships']}")
        print(f"LOCATED_IN : {import_stats['located_in_relationships']}")

        report = {
            "mode": mode,
            "database": database,
            "source_csv": str(args.poi_csv),
            "radius_m": args.radius_m,
            "counts": {
                "pois": len(pois),
                "categories": len(category_counts),
                "relationships_raw": len(edges),
                "bairro_nodes": import_stats["bairro_nodes"],
                "near_relationships": import_stats["near_relationships"],
                "located_in_relationships": import_stats["located_in_relationships"],
                "pois_without_bairro": import_stats["pois_without_bairro"],
            },
            "category_counts": category_counts,
            "bairro_summary": bairros,
            "nexusdb_ids": ids,
            "algorithms": algorithms,
            "notes": [
                "POIs were loaded from latitude/longitude already present in the CSV.",
                "Coordinates are reprojected to EPSG:31983 before distance calculations.",
                "NEAR is straight-line Euclidean proximity, not pedestrian travel time.",
                "LOCATED_IN is created only when the municipal source provides a bairro attribute; the demo does not infer bairro boundaries.",
                "For accessibility studies use street/GTFS network distance or City2Graph metapaths.",
            ],
        }

    else:
        if args.geocode_csv:
            demand, facility = geocode_layers(args.geocode_csv)
            mode = "geocodebr"
        else:
            demand, facility = fixture_layers()
            mode = "fixture"

        edges = build_access_edges(demand, facility, args.radius_m)

        print(f"Mode       : {mode}")
        print(f"Demand     : {len(demand)}")
        print(f"Facilities : {len(facility)}")
        print(f"Edges      : {len(edges)}")
        print(f"Radius     : {args.radius_m:.1f} m")
        print(f"Database   : {database}")

        # The create statement is sent through the Cypher-like endpoint. The same
        # credentials are then reused with the new database in X-Database.
        client.cypher(f"CREATE DATABASE {database}")

        ids = import_graph(client, demand, facility, edges)
        algorithms = run_algorithms(client)

        report = {
            "mode": mode,
            "database": database,
            "radius_m": args.radius_m,
            "counts": {
                "demand": len(demand),
                "facility": len(facility),
                "relationships": len(edges),
            },
            "nexusdb_ids": ids,
            "algorithms": algorithms,
            "notes": [
                "Fixture coordinates are synthetic." if mode == "fixture"
                else "Coordinates were resolved with geocodebr/CNEFE.",
                "CAN_REACH is straight-line proximity, not pedestrian travel time.",
            ],
        }

    args.output.mkdir(parents=True, exist_ok=True)
    path = args.output / "report.json"
    path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

    print()
    print("Algorithms completed:")
    for name, payload in algorithms.items():
        print(f"  {name:22s} {payload['elapsed_ms']:9.3f} ms")
    print(f"Report     : {path.resolve()}")
    print(f"Preserved DB: {database}")


if __name__ == "__main__":
    main()
